---
title: "R Notebook"
output: html_notebook
---

```{r}
library(tidyverse)
library(broom)
library(networkD3)
library(plotly)

mainDir <- getwd()
dataDir <- "datasets"
plotDir <- "plots"

demoMap <- read.csv(file.path(mainDir,dataDir,"PSES2018_Demographic_Mapping.csv"))

TBSdata <- pses2018 %>%
  filter(LEVEL1ID == "26" & SURVEYR == 2018) %>%
  mutate(DemoQ = ifelse(is.na(BYCOND),"TBS",word(BYCOND, 1, sep = " ="))) %>%
  mutate(DKNA = (ifelse(is.na(ANSWER6),0,ANSWER6)+ifelse(is.na(ANSWER7),0,ANSWER7))) %>%
  mutate(notDKNA_n = (100-DKNA)/100*ANSCOUNT) %>%
  mutate(positive_n = round(POSITIVE/100*notDKNA_n),0) %>%
  mutate(neutral_n = round(NEUTRAL/100*notDKNA_n),0) %>%
  mutate(negative_n = round(NEGATIVE/100*notDKNA_n),0) %>%
  drop_na(positive_n,negative_n) %>%
  mutate(neutralNA = ifelse(is.na(neutral_n),TRUE,FALSE)) %>%
  #filter((positive_n + negative_n)>0) %>%
  #filter(neutralNA == FALSE) %>%
  select(QUESTION,DemoQ,BYCOND,#DESCRIP_E,DESCRIP_F,neutralNA
         positive_n,negative_n,neutral_n)

TBSdata$BYCOND[TBSdata$DemoQ == "TBS"] <- "TBS" 

TBSresiduals <- TBSdata %>%
  group_by(QUESTION,DemoQ) %>%
  gather("Sentiment","Freq",positive_n,negative_n,neutral_n) %>%
  do((function(x) augment(chisq.test(xtabs(Freq ~ Sentiment + BYCOND, data=.))))(.)) %>%
  ungroup()

TBSpvalues <- TBSdata %>%
  group_by(QUESTION,DemoQ) %>%
  gather("Sentiment","Freq",positive_n,negative_n,neutral_n) %>%
  do((function(x) tidy(chisq.test(xtabs(Freq ~ Sentiment + BYCOND, data=.))))(.)) %>%
  ungroup()

ChiSquares <- left_join(TBSresiduals,TBSpvalues, by=c("QUESTION","DemoQ")) %>%
  left_join(demoMap, by = "DemoQ") %>% 
  mutate(sentiment = recode(Sentiment, negative_n = "NEGATIVE", neutral_n = "NEUTRAL", positive_n = "POSITIVE"))

TBS_Xsq <- TBS.df %>%
  filter(LEVEL1ID == 26) %>%
  gather("sentiment","prop",POSITIVE,NEUTRAL,NEGATIVE) %>%
  select(QUESTION,TITLE_E,DemoQ,BYCOND,DESCRIP_E,sentiment,prop) %>%
  left_join(select(ChiSquares,QUESTION,DemoQ,DemoQ_E,BYCOND,p.value,sentiment,.stdres,.observed),
            by=c("QUESTION","DemoQ","BYCOND","sentiment")) 
  
significant <- TBS_Xsq %>%
  filter(p.value <= 0.05 & 
           .stdres >= 2 & 
           sentiment %in% c("NEGATIVE","POSITIVE")) %>%
  select(QUESTION,TITLE_E,DemoQ_E,BYCOND,DESCRIP_E,p.value,sentiment,.stdres,.observed) %>%
  arrange(TITLE_E,BYCOND,p.value)

DemQpairs <- distinct(significant,TITLE_E,DESCRIP_E)
```

```{r}
pairs <- distinct(significant,TITLE_E,DESCRIP_E,.stdres, p.value) 

nodes <- pairs %>%
  gather("group","node") %>%
  distinct() %>%
  mutate(nodeID = row_number()-1)

links_quest <- pairs %>%
  select(node = TITLE_E) %>%
  left_join(nodes, by = "node") %>%
  select(question = nodeID)

links_demo <- pairs %>%
  select(node = DESCRIP_E) %>%
  left_join(nodes, by = "node") %>%
  select(demographic = nodeID)

links_value <- select(pairs, residuals = .stdres, p.value)

links <- bind_cols(links_quest,links_demo,links_value)

forceNetwork(Links = links,
             Nodes = nodes,
             Source = "demographic",
             Target = "question",
             Value = "residuals",
             NodeID = "node",
             Group =  "group",
             colourScale = JS("d3.scaleOrdinal(d3.schemeCategory10);"),
             height = 600,
             width = 800,
             opacity = 0.9,
             opacityNoHover = 0.3,
             legend = TRUE)

simpleNetwork(DemQpairs)
```

```{r, fig.width = 12, fig.height = 12}
balloon_neg <- filter(significant, sentiment == "NEGATIVE")

ggplot(balloon_neg, aes(x = DESCRIP_E, y = QUESTION)) +
  geom_point(aes(size=.stdres,colour=p.value)) +
  scale_colour_distiller(type = "seq", palette = "YlOrRd") +
  theme_bw() +
  theme(panel.border     = element_blank()) +
  # Remove just about everything from the y axis
  theme(axis.title.y     = element_blank()) +
  #theme(panel.grid.major.y = element_blank()) +
  theme(panel.grid.minor.y = element_blank()) +
  # Remove a few things from the x axis and increase font size
  theme(axis.title.x     = element_blank()) +
  theme(panel.grid.major = element_line(colour = "grey80")) +
  theme(axis.text.x  = element_text(angle = 90, vjust = 0.5, hjust = 1)) +
  # Remove x & y tick marks
  theme(axis.ticks       = element_blank()) +
  # Format title & subtitle
  theme(plot.title       = element_text(size=14, face = "bold", hjust = 0.5, vjust = 0)) +
  theme(plot.subtitle    = element_text(hjust = 0.5))

ggsave("PSES2018@TBS - ChiSquare Analysis.pdf", height = 15, width = 12, useDingbats=FALSE)
```

```{r, fig.width = 12, fig.height = 15}
balloon_pos <- filter(significant, sentiment == "POSITIVE")

ggplot(balloon_pos, aes(x = DESCRIP_E, y = QUESTION)) +
  geom_point(aes(size=.stdres,colour=p.value)) +
  scale_colour_distiller(type = "seq", palette = "BuGn") +
  theme_bw() +
  theme(panel.border     = element_blank()) +
  # Remove just about everything from the y axis
  theme(axis.title.y     = element_blank()) +
  #theme(panel.grid.major.y = element_blank()) +
  theme(panel.grid.minor.y = element_blank()) +
  # Remove a few things from the x axis and increase font size
  theme(axis.title.x     = element_blank()) +
  theme(panel.grid.major = element_line(colour = "grey80")) +
  theme(axis.text.x  = element_text(angle = 90, vjust = 0.5, hjust = 1)) +
  # Remove x & y tick marks
  theme(axis.ticks       = element_blank()) +
  # Format title & subtitle
  theme(plot.title       = element_text(size=14, face = "bold", hjust = 0.5, vjust = 0)) +
  theme(plot.subtitle    = element_text(hjust = 0.5))

ggsave("PSES2018@TBS - ChiSquare Analysis.pdf", height = 15, width = 12, useDingbats=FALSE)
```

```{r, fig.width = 12, fig.height = 15}
balloon <- TBS_Xsq %>%
  filter(p.value <= 0.05 & 
           .stdres >= 2) %>%
  mutate(DESCRIP_E = replace(DESCRIP_E, DESCRIP_E == "First official language - French", "First OL: French")) %>%
  mutate(DESCRIP_E = replace(DESCRIP_E, DESCRIP_E == "First official language - English", "First OL: English")) %>%
  mutate(descrip_e_cut = paste0(substr(DESCRIP_E,1,15),"...")) %>%
  arrange(BYCOND) %>%
  mutate(descrip_e_cut = factor(descrip_e_cut, levels = unique(descrip_e_cut))) %>%
  select(QUESTION,TITLE_E,DemoQ_E,BYCOND,DESCRIP_E,descrip_e_cut,p.value,sentiment,.stdres,.observed)
  
#balloon[balloon == "First official language - French"] <- "First OL: French"
#balloon[balloon == "First official language - English"] <- "First OL: English"

bp <- ggplot(balloon,aes(x = descrip_e_cut, y = reorder(QUESTION,desc(QUESTION)), 
                         text = paste0(sentiment,"<br>",
                                      TITLE_E,"<br>",
                                      "Demographic: ", DemoQ_E, " - ", DESCRIP_E, " (n=",.observed,")","<br>",
                                      " (standardized residual = ",round(.stdres,2),", p-value = ", round(p.value,5),")"
                                      ))) +
  geom_point(aes(size=.stdres, colour=sentiment,alpha=(0.05-p.value))) +
  scale_colour_brewer(palette = "Set1") +
  labs(title = "PSES@TBS 2018 - Sentiment by Question and Demographic",
       subtitle = "Results of chi-square tests on sentiment responses by demogrphic for every PSES question at TBS.\nEach dot represents a significant finding (p < 0.05, standardized residual > 2).\nColours denote sentiment, size correspond to standardized residuals, opaqueness relfects the p-value.",
       caption = "Data from the 2018 Public Service Employee Survey") + 
  theme_bw() +
  theme(panel.border     = element_blank()) +
  # Remove just about everything from the y axis
  theme(axis.title.y     = element_blank()) +
  #theme(panel.grid.major.y = element_blank()) +
  theme(panel.grid.minor.y = element_blank()) +
  # Remove a few things from the x axis and increase font size
  theme(axis.title.x     = element_blank()) +
  theme(panel.grid.major = element_line(colour = "grey90")) +
  theme(axis.text.x  = element_text(angle = 90, vjust = 0.5, hjust = 1)) +
  # Remove x & y tick marks
  theme(axis.ticks       = element_blank()) +
  # Format title & subtitle
  theme(plot.title       = element_text(size=14, face = "bold", hjust = 0.5, vjust = 0)) +
  theme(plot.subtitle    = element_text(hjust = 0.5))

bp <- ggplotly(bp, tooltip = c("text"))

htmlwidgets::saveWidget(as.widget(bp), file.path(mainDir,plotDir,"ChiSquare_BalloonChart.html"))
```

```{r}
# Load data
data(MisLinks)
data(MisNodes)

# Plot
forceNetwork(Links = MisLinks, Nodes = MisNodes,
            Source = "source", Target = "target",
            Value = "value", NodeID = "name",
            Group = "group", opacity = 0.8)
```

```{r}
ggplot(significant, aes(p.value)) +
  geom_freqpoly(binwidth=0.005)
```

```{r}
TBS_Binary <- TBSdata %>%
  filter(neutralNA == TRUE) %>%
  group_by(QUESTION,DemoQ) %>%
  do(Xsq = (function(x) chisq.test(x[,6:7]))(.)) %>%
  ungroup() %>%
  mutate(p.value = as.double(sapply(Xsq,"[", "p.value")))

TBS_PNN <- TBSdata %>%
  filter(neutralNA == FALSE) %>%
  group_by(QUESTION,DemoQ) %>%
  do(Xsq = (function(x) chisq.test(x[,6:8]))(.)) %>%
  # augment(Xsq)
  ungroup() %>%
  mutate(p.value = as.double(sapply(Xsq,"[", "p.value")))

ChiSquares <- bind_rows(TBS_Binary,TBS_PNN)
```