---
title: "PSES2018@TBS Sectors by Indicataor - Score 100 Bar Charts"
output: html_document
---

```{r setup, include=FALSE}
library(scales)
library(readxl)
library(tidyverse)
library(ggrepel)
library(grid)
library(cowplot)

mainDir <- getwd()
dataDir <- "datasets"
plotDir <- "plots"
ss5File_2018 <- file.path(mainDir,dataDir,"pses2018_ss5.csv")
ss5File_2017 <- file.path(mainDir,dataDir,"pses2017_ss5.csv")
ss5URL_2018 <- "https://www.canada.ca/content/dam/tbs-sct/documents/datasets/pses-saff/2018/2018_PSES_SAFF_Subset-5_Sous-ensemble-5.csv" # Due for release in March 2018
ss5URL_2017 <- "https://www.canada.ca/content/dam/tbs-sct/documents/datasets/pses-saff/2017/2017_PSES_SAFF_Subset-5_Sous-ensemble-5.csv" # Due for release in March 2018

ifelse(!dir.exists(file.path(mainDir, dataDir)), dir.create(file.path(mainDir, dataDir)), FALSE)
ifelse(!dir.exists(file.path(mainDir, plotDir)), dir.create(file.path(mainDir, plotDir)), FALSE)

if(!file.exists(ss5File_2018)) {download.file(ss5URL_2018,ss5File_2018)}
if(!file.exists(ss5File_2017)) {download.file(ss5URL_2017,ss5File_2017)}

if(!exists("ss5_2018")) {ss5_2018 <- read.csv(ss5File_2018, na.strings = "9999")}
if(!exists("ss5_2017")) {ss5_2017 <- read.csv(ss5File_2017, na.strings = "9999")}
if(!exists("indicatorMap")) {
  indicatorMap <- read.csv(file.path(mainDir,dataDir,"PSES2018_Indicator_Mapping.csv"))}

Qcorr <- read.csv(file.path(mainDir,dataDir,"PSES2018_Question_Corr.csv"), na.strings = "N/A") %>%
  mutate(PSES_2017 = ifelse(PSES_2018 == "48","63",as.character(PSES_2017))) %>% # Add harassment question from 2017
  mutate(PSES_2017 = ifelse(PSES_2018 == "55","75",as.character(PSES_2017))) %>% # Add discrimination question from 2017
  gather("PSES_year","QUESTION",-QUESTION_E) %>%
  mutate(QUESTION = ifelse(is.na(QUESTION),NA,
                           paste0("Q",
                           ifelse(QUESTION %in% c("1","2","3","4","5","6","7","8","9"),"0",""),
                           QUESTION))) %>%
  spread(PSES_year,QUESTION) %>%
  arrange(PSES_2018)

sectors_2017 <- ss5_2017 %>%
  filter(LEVEL1ID %in% c(0,26)) %>%
  mutate(QUESTION = substring(QUESTION,3)) %>%
  left_join(select(Qcorr,QUESTION="PSES_2017",Q2018="PSES_2018"), by = "QUESTION") %>%
  filter(!is.na(Q2018)) %>%
  select(DESCRIP_E,QUESTION="Q2018",s100_2017="SCORE100",agree_2017="AGREE")

question100s <- ss5_2018 %>%
  filter(LEVEL1ID %in% c(0,26)) %>%
  left_join(indicatorMap, by = "QUESTION") %>%
  mutate(unitcode = ifelse(BYCOND == "",
                           ifelse(LEVEL1ID == 26, "TBS","PS"),
                           word(BYCOND, 2, sep = " = "))) %>%
  #filter(!(is.na(SCORE100))) %>%
  left_join(sectors_2017, by = c("QUESTION","DESCRIP_E")) %>%
  rename(s100_2018 = "SCORE100") %>%
  gather("SURVEYR","SCORE100",s100_2018,s100_2017) %>%
  mutate(SURVEYR = substring(SURVEYR,6)) %>%
  #filter(!(is.na(SCORE100))) %>%
  group_by(SURVEYR,unitcode) %>%
  mutate(overall100 = mean(SCORE100, na.rm = TRUE)) %>%
  ungroup()

score100s <- question100s %>%
  group_by(SURVEYR,unitcode,DESCRIP_E,DESCRIP_F,INDICATORID,INDICATORENG,INDICATORFRA,overall100) %>%
  summarise(indicator100 = mean(SCORE100, na.rm = TRUE)) %>%
  ungroup()

test <- ss5_2018 %>%
  filter(LEVEL1ID == 26 & LEVEL2ID == 0 & !(is.na(SCORE100))) %>%
  mutate(mean100 = mean(SCORE100, na.rm = TRUE))

```

```{r cars}
score100s_TBS <- pses2018_units %>%
  mutate(unitcode = ifelse(is.na(BYCOND),"TBS",word(BYCOND, 2, sep = " = "))) %>%
  filter(!(unitcode %in% c("200","303","304","201","202","999")) & !(is.na(SCORE100))) %>%
  group_by(unitcode) %>%
  mutate(overall100 = mean(SCORE100)) %>%
  ungroup() %>%
  group_by(unitcode,DESCRIP_E,DESCRIP_F,INDICATORID,INDICATORENG,INDICATORFRA,overall100) %>%
  summarise(indicator100 = mean(SCORE100)) %>%
    ungroup()
    
score100s_PS <- ss1 %>%
  left_join(indicatorMap, by = "QUESTION") %>%
  filter(LEVEL1ID == "0" & SURVEYR == 2018 & !(is.na(SCORE100))) %>%
  mutate(unitcode = "PS") %>%
  mutate(overall100 = mean(SCORE100)) %>%
  ungroup() %>%
  group_by(unitcode,DESCRIP_E,DESCRIP_F,INDICATORID,INDICATORENG,INDICATORFRA,overall100) %>%
  summarise(indicator100 = mean(SCORE100)) %>%
  ungroup()

score100s <- bind_rows(score100s_TBS,score100s_PS) %>%
  filter()

score100s <- score100s %>% mutate(INDICATORENG = replace_na(INDICATORENG,"TBS QUESTIONS"))
```

```{r pressure, echo=FALSE, fig.height = 8, fig.width = 10}
ggplot(score100s, aes(x = fct_reorder(DESCRIP_E,overall100), y = indicator100,fill = INDICATORENG)) +
  geom_bar(position="dodge", stat="identity") +
  scale_x_discrete(labels = wrap_format(30)) +
  scale_x_discrete(labels=c("Public Service"=expression(bold("Public Service")),
                            "Treasury Board of Canada Secretariat"=expression(bold("Treasury Board of Canada Secretariat")),
                            parse=TRUE)) +
  scale_fill_brewer(palette = "Set2") +
  coord_flip() +
  labs(#title = "TBS Sectors by Indicator",
       #subtitle = str_wrap("Each row displays the mean scores out of 100 for each question grouping.Sectors are ordred from highest overall mean score to lowest.TBS and Public Service numbers are included for reference.",
       #                   80),
       caption = "2018 Public Service Employee Survey",
       x = "Sector",
       y = "Mean score out of 100") +
  theme_minimal() +
  theme(axis.title = element_blank(),
        legend.title = element_blank(),
        legend.position = "bottom")

ggsave("TBS Sectors by Indicator - lines.png", height = 8, width = 10)
```

```{r, fig.height = 8, fig.width = 12}
score100s_overall <- score100s %>%
  filter(SURVEYR == 2018) %>%
  select(DESCRIP_E,INDICATORENG,indicator100,overall100) %>%
  mutate(OVERALL = overall100) %>%
  spread(INDICATORENG,indicator100) %>%
  gather(INDICATORENG,indicator100,-DESCRIP_E,-overall100) %>%
  mutate(INDICATORENG = fct_relevel(INDICATORENG, "OVERALL")) %>%
  mutate(DESCRIP_E = fct_reorder(DESCRIP_E,overall100))

ggplot(score100s_overall, aes(x = DESCRIP_E, y = indicator100, fill = INDICATORENG)) +
  geom_bar(position="dodge", stat="identity") +
  scale_x_discrete(labels=c("Public Service"=expression(bold("Public Service")),
                            "Treasury Board of Canada Secretariat"=expression(bold("Treasury Board of Canada Secretariat")),
                            parse=TRUE)) +
  scale_fill_brewer(palette = "Set2") +
  geom_text(aes(y=indicator100,label=round(indicator100,0)), hjust = 1.1, fontface = "bold", colour = "white") +
  coord_flip() +
  labs(caption = "2018 Public Service Employee Survey") +
  facet_grid(~INDICATORENG, labeller = labeller(INDICATORENG = label_wrap_gen(15))) +
  theme_minimal() +
  theme(axis.title = element_blank(),
        legend.title = element_blank(),
        legend.position = "none",
        axis.text.x = element_blank(),
        panel.grid = element_blank())

ggsave("TBS Sectors by Indicator 2018 - facets.png", height = 8, width = 12)
```

```{r TBS Sectors - Facets, fig.height = 8, fig.width = 12}
score100s_overall <- score100s %>%
  filter(!(unitcode %in% c("200","303","304","201","202","999"))) %>%
  select(SURVEYR,DESCRIP_E,INDICATORENG,indicator100,overall100) %>%
  mutate(OVERALL = overall100) %>%
  spread(INDICATORENG,indicator100) %>%
  gather(INDICATORENG,indicator100,-DESCRIP_E,-overall100,-SURVEYR) %>%
  mutate(INDICATORENG = fct_relevel(INDICATORENG, "OVERALL")) %>%
  mutate(DESCRIP_E = ifelse(DESCRIP_E == "Public Service",
                            "bold(Public Service)",
                            ifelse(DESCRIP_E == "Treasury Board of Canada Secretariat",
                                   "bold(Treasury Board of Canada Secretariat)",
                                   DESCRIP_E))) %>%
  mutate(DESCRIP_E = gsub(" ","~",DESCRIP_E)) %>%
  mutate(DESCRIP_E = gsub(",","",DESCRIP_E)) %>%
  mutate(DESCRIP_E = gsub("'","",DESCRIP_E)) %>%
  arrange(desc(SURVEYR),desc(overall100)) %>% 
  mutate(DESCRIP_E = factor(DESCRIP_E,unique(DESCRIP_E)))


TBSfacets <- ggplot(score100s_overall, aes(x = SURVEYR, y = indicator100, fill = INDICATORENG)) +
  geom_bar(position="dodge", stat="identity", width = 1, aes(alpha = SURVEYR)) +
  scale_y_continuous(limits = c(0,100)) +
  scale_fill_brewer(palette = "Set2") +
  scale_colour_brewer(palette = "Set2") +
  scale_alpha_manual(values = c(.67,1)) +
  geom_text(aes(y=indicator100, label=round(indicator100,0), colour = INDICATORENG),
            size = 3, hjust = -0.3, vjust = 0.5, fontface = "bold") +
  geom_text(aes(label=SURVEYR),
            y = 0, size = 3, hjust = -0.1, vjust = 0.5, colour = "white") +
  coord_flip() +
  labs(caption = "2018 Public Service Employee Survey") +
  facet_grid(DESCRIP_E~INDICATORENG, 
             switch = "y", 
             labeller = labeller(
               INDICATORENG = label_wrap_gen(15), 
               DESCRIP_E = label_parsed)) +
  theme_minimal() +
  theme(axis.title = element_blank(),
        legend.title = element_blank(),
        legend.position = "none",
        axis.text = element_blank(),
        axis.ticks.y.right = element_blank(),
        panel.grid = element_blank(),
        strip.text.y = element_text(angle = 180, hjust = 1),
        panel.spacing.y = unit(0.5,"mm"))

TBSfacets

ggsave(plot = TBSfacets, "TBS Sectors by Indicator - facets.pdf", height = 8, width = 12)
```

```{r TBS Sectors - Facets & Descriptions, fig.height = 8, fig.width = 13.5}
title.grb <- textGrob("TBS Sectors by PSES Indicator (2017-2018)", hjust = 0.5, gp=gpar(fontsize=16, col ="black",
                                                                                        fontface = "bold"))

graph.grb <- plot_grid(title.grb,TBSfacets, ncol = 1, align = "v", rel_heights = c(1,19))

howto_ttl.grb <- textGrob("\nHow to read \nthis graph", hjust = 0.5, gp=gpar(fontsize=12, col ="black", fontface = "bold"))

howto_txt.grb <- textGrob("
Each row represents a TBS sector.
Overall TBS and Public Service rows 
are also provided for comparison.\n 
Each column represents a grouping of
PSES questions by theme - an \"indicator\".
The OVERALL column is the grouping of 
all PSES questions.\n
Sector rows are ordered using the 2018
OVERALL column from highest to lowest
score. The number and length of each bar
represents the average score of the
questions in that grouping, in that sector.\n
The score is based on the \"Score 100\"
measure for each question. It is the
average of question responses using
these weights: 
Very Positive = 100,
Positive = 75,
Neutral = 50,
Negative = 25,
Very Negative = 0.\n
Example:
A score of 52 for \"Employee Engagement\"
means that the average \"Score 100\"
of the questions under that theme
(5, 9, 10, 14, 43, 44 and 45)
for that sector was 52 out of 100 -
closest to \"Neutral\".",
                          hjust = 0.5, gp=gpar(fontsize=6, col ="black"))

limits_ttl.grb <- textGrob("\nLimitations", hjust = 0.5, gp=gpar(fontsize=12, col ="black", fontface = "bold"))

limits_txt.grb <- textGrob("
Not all responses rates were the same
for all sectors (HRD has this available).\n
The \"Score 100\" measure does not reflect
the distribution of responses. Example:
50 people scoring very positive and
50 people scoring very negative
(50%*100 + 50%*0 = 50)
is identical to 100 people
scoring neutral
(100%*50 = 50).\n
The \"Score 100\" measure makes
assumptions based on its weighting
(described above).\n
The \"indicators\" are not stable - 
PSES questions change from year to year.\n
\"Indicator\" questions are weighted equally.
",
                          hjust = 0.5, gp=gpar(fontsize=6, col ="black"))

descrip.grb <- plot_grid(howto_ttl.grb,howto_txt.grb,limits_ttl.grb,limits_txt.grb, ncol = 1, align = "v", rel_heights = c(1,10,1,6))

facets.grb <- plot_grid(graph.grb,descrip.grb, rel_widths = c(7,1))

facets.grb

ggsave(plot = facets.grb, "TBS Sectors by Indicator - facets.pdf", height = 8, width = 13.5)

```

```{r TBS Sectors - Facets FR, fig.height = 8, fig.width = 13.5}
score100s_overall_FR <- score100s %>%
  filter(!(unitcode %in% c("200","303","304","201","202","999"))) %>%
  select(SURVEYR,DESCRIP_F,INDICATORFRA,indicator100,overall100) %>%
  mutate(SOMMAIRE = overall100) %>%
  spread(INDICATORFRA,indicator100) %>%
  gather(INDICATORFRA,indicator100,-DESCRIP_F,-overall100,-SURVEYR) %>%
  mutate(INDICATORFRA = fct_relevel(INDICATORFRA, "SOMMAIRE")) %>%
  mutate(DESCRIP_F = ifelse(DESCRIP_F == "Fonction publique",
                            "bold(Fonction publique)",
                            ifelse(DESCRIP_F == "Secrétariat du Conseil du Trésor du Canada",
                                   "bold(Secrétariat du Conseil du Trésor du Canada)",
                                   as.character(DESCRIP_F)))) %>%
  mutate(DESCRIP_F = gsub(" ","~",DESCRIP_F)) %>%
  mutate(DESCRIP_F = gsub(",","",DESCRIP_F)) %>%
  mutate(DESCRIP_F = gsub("'","",DESCRIP_F)) %>%
  arrange(desc(SURVEYR),desc(overall100)) %>% 
  mutate(DESCRIP_F = factor(DESCRIP_F,unique(DESCRIP_F)))


TBSfacets_FR <- ggplot(score100s_overall_FR, aes(x = SURVEYR, y = indicator100, fill = INDICATORFRA)) +
  geom_bar(position="dodge", stat="identity", width = 1, aes(alpha = SURVEYR)) +
  scale_y_continuous(limits = c(0,100)) +
  scale_fill_brewer(palette = "Set2") +
  scale_colour_brewer(palette = "Set2") +
  scale_alpha_manual(values = c(.67,1)) +
  geom_text(aes(y=indicator100, label=round(indicator100,0), colour = INDICATORFRA),
            size = 3, hjust = -0.3, vjust = 0.5, fontface = "bold") +
  geom_text(aes(label=SURVEYR),
            y = 0, size = 3, hjust = -0.1, vjust = 0.5, colour = "white") +
  coord_flip() +
  labs(caption = "Sondage auprès des fonctionnaires fédéraux 2018") +
  facet_grid(DESCRIP_F~INDICATORFRA, 
             switch = "y", 
             labeller = labeller(
               INDICATORFRA = label_wrap_gen(15), 
               DESCRIP_F = label_parsed)) +
  theme_minimal() +
  theme(axis.title = element_blank(),
        legend.title = element_blank(),
        legend.position = "none",
        axis.text = element_blank(),
        axis.ticks.y.right = element_blank(),
        panel.grid = element_blank(),
        strip.text.y = element_text(angle = 180, hjust = 1),
        panel.spacing.y = unit(0.5,"mm"))

titleFR.grb <- textGrob("Secteurs du SCT par indicateur SAFF (2017-2018)", hjust = 0.5, gp=gpar(fontsize=16, col ="black",
                                                                                        fontface = "bold"))
graphFR.grb <- plot_grid(titleFR.grb,TBSfacets_FR, ncol = 1, align = "v", rel_heights = c(1,19))

howto_ttlFR.grb <- textGrob("\nComment lire \nce graphique", hjust = 0.5, gp=gpar(fontsize=12, col ="black", fontface = "bold"))

howto_txtFR.grb <- textGrob("
Chaque ligne représente un secteur du 
SCT. Des rangées globales pour le SCT 
et la fonction publique sont également 
fournies à titre de comparaison. \n
Chaque colonne représente un groupe de
questions sur le SAFF par thème, dit un
un « indicateur ». La colonne SOMMAIRE
est le regroupement de toutes les 
questions sur le SAFF. \n
Les rangées de secteurs sont classées
à l'aide de la colonne SOMMAIRE 2018
en ordre décroissant. Le chiffre et la
longueur de chaque barre représente
le score moyen des questions dans ce 
groupe, dans ce secteur. \n
Le score est basé sur le « Score 100 »
mesuré pour chaque question. C'est la
moyenne des réponses aux questions en
utilisant ces poids:
Très positif = 100,
Positif = 75,
Neutre = 50,
Négatif = 25,
Très négatif = 0. \n
Exemple:
Un score de 52 pour « Engagement des
employés » signifie que la moyenne
du « Score 100 » des questions sous 
ce thème (5, 9, 10, 14, 43, 44 et 45)
pour ce secteur était de 52 sur 100,
soit plus proche de « Neutre ».",
                          hjust = 0.5, gp=gpar(fontsize=6, col ="black"))

limits_ttlFR.grb <- textGrob("\nLimitations", hjust = 0.5, gp=gpar(fontsize=12, col ="black", fontface = "bold"))

limits_txtFR.grb <- textGrob("
Tous les taux de réponse n'étaient pas
les mêmes pour tous les secteurs
(la DRH les a de disponible). \ n
La mesure « Score 100 » ne reflète pas
la distribution des réponses. Exemple:
50 personnes très positives et
50 personnes très négatives
(50% * 100 + 50% * 0 = 50)
est identique à 100 personnes
marquant neutre
(100% * 50 = 50). \ N
La mesure « Score 100 » fait des
hypothèses basées sur la pondération
(décrit ci-dessus). \ n
Les « indicateurs » ne sont pas stables;
les questions du SAFF changent d'année 
en année. \ N
Les questions qui contituent les 
« indicateurs » ne sont pas pondérées.
",
                          hjust = 0.5, gp=gpar(fontsize=6, col ="black"))

descripFR.grb <- plot_grid(howto_ttlFR.grb,howto_txtFR.grb,limits_ttlFR.grb,limits_txtFR.grb, ncol = 1, align = "v", rel_heights = c(1,10,1,6))

facetsFR.grb <- plot_grid(graphFR.grb,descripFR.grb, rel_widths = c(7,1))

facetsFR.grb

ggsave(plot = facetsFR.grb, "Secteurs du SCT par indicateur - facettes FR.pdf", height = 8, width = 13.5)
```


```{r OCG Sectors - Facets, fig.height = 4, fig.width = 12}
score100s_overall <- score100s %>%
  filter(unitcode %in% c(NA,"304","405","406","407","408")) %>%
  select(SURVEYR,DESCRIP_E,INDICATORENG,indicator100,overall100) %>%
  mutate(OVERALL = overall100) %>%
  spread(INDICATORENG,indicator100) %>%
  gather(INDICATORENG,indicator100,-DESCRIP_E,-overall100,-SURVEYR) %>%
  mutate(INDICATORENG = fct_relevel(INDICATORENG, "OVERALL")) %>%
  mutate(DESCRIP_E = ifelse(DESCRIP_E == "Public Service",
                            "bold(Public Service)",
                            ifelse(DESCRIP_E == "Treasury Board of Canada Secretariat",
                                   "bold(Treasury Board of Canada Secretariat)",
                                   ifelse(DESCRIP_E == "Office of the Comptroller General",
                                   "bold(Office of the Comptroller General)",DESCRIP_E)))) %>%
  mutate(DESCRIP_E = gsub(" ","~",DESCRIP_E)) %>%
  mutate(DESCRIP_E = gsub(",","",DESCRIP_E)) %>%
  mutate(DESCRIP_E = gsub("'","",DESCRIP_E)) %>%
  arrange(desc(SURVEYR),desc(overall100)) %>% 
  mutate(DESCRIP_E = factor(DESCRIP_E,unique(DESCRIP_E)))


ggplot(score100s_overall, aes(x = SURVEYR, y = indicator100, fill = INDICATORENG)) +
  geom_bar(position="dodge", stat="identity", width = 1, aes(alpha = SURVEYR)) +
  scale_y_continuous(limits = c(0,100)) +
  scale_fill_brewer(palette = "Set2") +
  scale_colour_brewer(palette = "Set2") +
  scale_alpha_manual(values = c(.67,1)) +
  geom_text(aes(y=indicator100, label=round(indicator100,0), colour = INDICATORENG),
            size = 3, hjust = -0.3, vjust = 0.5, fontface = "bold") +
  geom_text(aes(label=SURVEYR),
            y = 0, size = 3, hjust = -0.1, vjust = 0.5, colour = "white") +
  coord_flip() +
  labs(caption = "2018 Public Service Employee Survey") +
  facet_grid(DESCRIP_E~INDICATORENG, 
             switch = "y", 
             labeller = labeller(
               INDICATORENG = label_wrap_gen(15), 
               DESCRIP_E = label_parsed)) +
  theme_minimal() +
  theme(axis.title = element_blank(),
        legend.title = element_blank(),
        legend.position = "none",
        axis.text = element_blank(),
        axis.ticks.y.right = element_blank(),
        panel.grid = element_blank(),
        strip.text.y = element_text(angle = 180, hjust = 1),
        panel.spacing.y = unit(0.5,"mm"))



ggsave("OCG Sectors by Indicator - facets.pdf", height = 4, width = 12)
```



```{r Sector Card - slope, echo=FALSE, fig.height=4, fig.width=5}

thisSector <- 301
thisAbbr_E <- "OCIO"

sectorData <- score100s %>%
  filter(unitcode %in% c(thisSector,"TBS")) %>%
  mutate(abbr_E = ifelse(unitcode == thisSector, thisAbbr_E, unitcode))

#sectorName_E <- sectorData$DESCRIP_E[[1]]
sectorName_E <- "Office of the Chief Information Officer"

ttl_E <- paste0("PSES@TBS 2018 - ",sectorName_E)

slopeTheme <- list(
  theme_bw(),
  # Format tweaks
  # Remove the legend
  theme(legend.position = "none"),
  # Remove the panel border
  theme(panel.border     = element_blank()),
  # Remove just about everything from the y axis
  theme(axis.title.y     = element_blank()),
  theme(axis.text.y      = element_blank()),
  theme(panel.grid.major.y = element_blank()),
  theme(panel.grid.minor.y = element_blank()),
  # Remove a few things from the x axis and increase font size
  theme(axis.title.x     = element_blank()),
  theme(panel.grid.major.x = element_blank()),
  theme(axis.text.x.top      = element_text(size=10, face="bold")),
  # Remove x & y tick marks
  theme(axis.ticks       = element_blank()),
  # Format title & subtitle
  theme(text = element_text(colour="grey30")),
  theme(plot.title       = element_text(size=10, hjust = 0.5)),
  theme(plot.subtitle    = element_text(hjust = 0.5)),
  # Change canvas size
  #theme(plot.margin = margin(t = .2, r = 1, b = .2, l = 1, "in")) +
  # Put facet labels on the left and horizontal
  theme(strip.text.y = element_text(angle = 180, size = 8)),
  theme(strip.text.x = element_text(size = 10, colour = "grey30", face="italic")),
  theme(strip.background = element_blank())
  #theme(panel.background = element_rect(fill = "grey95"))
)

slp <- ggplot(sectorData, aes(x = SURVEYR, y = round(indicator100,0), group = INDICATORENG)) +
  facet_grid(INDICATORENG~., scales = "free_y", switch = "y", labeller = label_wrap_gen(10)) + 
  geom_line(data = sectorData %>% filter(unitcode == thisSector),
            aes(color = INDICATORENG), alpha = 1,linetype = 1, size = 1) +
  geom_line(data = sectorData %>% filter(unitcode == "TBS"),
            aes(color = INDICATORENG), alpha = 0.67,linetype = 1, size = 1) +
  scale_colour_brewer(palette = "Set2") +
  geom_text_repel(data = sectorData %>% filter(SURVEYR == 2017), 
                  aes(label = abbr_E, colour = INDICATORENG), 
                  hjust = 2, 
                  fontface = "bold", 
                  size = 3,
                  nudge_x = -1, 
                  direction = "y") +
  geom_text_repel(data = sectorData %>% filter(SURVEYR == 2018), 
                  aes(label = abbr_E, colour = INDICATORENG), 
                  hjust = -1, 
                  fontface = "bold", 
                  size = 3,
                  nudge_x = 1, 
                  direction = "y") +
  geom_point(colour = "white", size = 8, shape = 16) +
  geom_text(aes(label = round(indicator100,0), y = round(indicator100,0)),
            size = 3, colour = "grey30", fontface = "bold") +
  scale_alpha_manual(values = c(1,.67)) +
  # move the x axis labels up top
  scale_x_discrete(position = "top") +
  scale_y_continuous(expand = expand_scale(add = 1)) +
  slopeTheme

slp2 <- ggplot(sectorData, aes(x = SURVEYR, y = round(indicator100,0), group = INDICATORENG)) +
  facet_grid(.~abbr_E) + 
  geom_line(data = sectorData %>% filter(unitcode == thisSector),
            aes(color = INDICATORENG), alpha = 0.6,linetype = 1, size = 1) +
  geom_line(data = sectorData %>% filter(unitcode == "TBS"),
            aes(color = INDICATORENG), alpha = 0.6,linetype = 2, size = 1) +
  scale_colour_brewer(palette = "Set2") +
  geom_text_repel(data = sectorData %>% filter(SURVEYR == 2017), 
                  aes(label = str_wrap(paste0(INDICATORENG," (ind",INDICATORID,")"),10), colour = INDICATORENG), 
                  hjust = 2, 
                  fontface = "bold", 
                  size = 2,
                  nudge_x = -1, 
                  direction = "y") +
  geom_text_repel(data = sectorData %>% filter(SURVEYR == 2018), 
                  aes(label = str_wrap(paste0(INDICATORENG," (ind",INDICATORID,")"),10), colour = INDICATORENG), 
                  hjust = -1, 
                  fontface = "bold", 
                  size = 2,
                  nudge_x = 1, 
                  direction = "y") +
  geom_point(colour = "white", size = 8, shape = 16) +
  geom_text(aes(label = round(indicator100,0), y = round(indicator100,0)),
            size = 3, colour = "grey30", fontface = "bold") +
  #scale_alpha_manual(values = c(1,.67)) +
  # move the x axis labels up top
  scale_x_discrete(position = "top", expand = expand_scale(add = 1)) +
  scale_y_continuous(expand = expand_scale(add = 1)) +
  slopeTheme

# Code to turn off clipping
#gt <- ggplotGrob(slp)
#gt$layout$clip[gt$layout$name == "panel"] <- "off"
#grid.draw(gt)

slp_ttl <- textGrob("Year-to-Year Score 100 Comparsion", gp=gpar(fontsize = 10, fontface = "bold", col = "grey30"))

slp.grb <- plot_grid(slp_ttl,slp2,nrow=2,rel_heights = c(1,12))
slp.grb
```

```{r Sector Card - Shifts, echo=FALSE, fig.height=8, fig.width=5}

sectorDeltas <- question100s %>%
  filter(unitcode %in% c(thisSector, "TBS")) %>%
  mutate(abbr_E = ifelse(unitcode == thisSector, thisAbbr_E, unitcode)) %>%
  select(INDICATORID,INDICATORENG,INDICATORFRA,QUESTION,TITLE_E,TITLE_F,
         unitcode,abbr_E,DESCRIP_E,DESCRIP_F,SURVEYR,SCORE100,AGREE) %>%
  spread(SURVEYR,SCORE100) %>%
  mutate(delta = `2018`-`2017`)

best10deltas <- filter(sectorDeltas, unitcode == thisSector & delta > 0) %>% top_n(10,delta) %>% select(QUESTION)
worst10deltas <- filter(sectorDeltas, unitcode == thisSector & delta < 0) %>% top_n(-10,delta) %>% select(QUESTION)


deltaTheme <- list( 
  theme_bw(),
  # Format tweaks
  # Remove the legend
  theme(legend.position = "none"),
  # Remove the panel border
  theme(panel.border     = element_blank()),
  # Remove just about everything from the y axis
  theme(axis.title.y     = element_blank()),
  theme(axis.text.y      = element_blank()),
  theme(panel.grid.major.y = element_blank()) +
  theme(panel.grid.minor.y = element_blank()),
  # Remove a few things from the x axis and increase font size
  theme(axis.title.x     = element_blank()),
  theme(panel.grid.minor.x = element_blank()),
  theme(panel.grid.major.x = element_blank()),
  theme(axis.text.x      = element_text(size = 6)),
  # Remove x & y tick marks
  theme(axis.ticks       = element_blank()),
  # Format title & subtitle
  theme(text = element_text(colour="grey30")),
  theme(plot.title       = element_text(size = 8, hjust = 0.5)),
  theme(plot.subtitle    = element_text(hjust = 0.5)),
  # Change canvas size
  #theme(plot.margin = margin(t = .2, r = 1, b = .2, l = 1, "in")) +
  # Put facet labels on the left and horizontal
  theme(strip.text.y = element_text(angle = 180, size = 6, hjust = 0)),
  theme(strip.background = element_blank())
  #theme(panel.background = element_rect(fill = "grey95")) +
)

bestData <- sectorDeltas %>%
  inner_join(best10deltas, by = "QUESTION") %>%
  filter(unitcode != "TBS")

best <- ggplot(data = bestData, x = abbr_E, group = abbr_E) +
  geom_col(aes(x = abbr_E, y = `2018`), colour = "grey80", fill = "#f7f7f7", width = 0.8) +
  geom_hline(aes(yintercept = `2017`), colour = "grey60") +
  geom_hline(aes(yintercept = `2018`), colour = "grey60") +
  geom_segment(aes(x = abbr_E, xend = abbr_E, y = `2017`, yend = `2018`, colour = delta),
               size = 1, linejoin = "mitre", arrow = arrow(length = unit(0.2, "cm"))) +
  #geom_point(aes(x = abbr_E, y = `2017`, alpha = abbr_E), size = 8, shape = 16, colour = "blue") +
  #geom_point(aes(x = abbr_E, y = `2018`, alpha = abbr_E), size = 8, shape = 16, colour = "red") +
  geom_text(aes(label = `2017`, x = abbr_E, y = `2017`),
            size = 3, colour = "grey30", fontface = "plain", hjust = 1.3, vjust = 0.5) +
  geom_text(aes(label = `2018`, x = abbr_E, y = `2018`),
            size = 3, colour = "grey30", fontface = "bold", hjust = -0.3, vjust = 0.5) +
  geom_text(aes(label = paste0("(+",delta,")"), x = abbr_E, y = `2018`, colour = delta),
            size = 3, fontface = "bold", hjust = -1, vjust = 0.5) +
  geom_text(aes(label = paste0("ind",INDICATORID), x = abbr_E, y = 0),
            size = 3, colour = "grey50", fontface = "plain", hjust = -0.1, vjust = 0.5) +
  coord_flip() +
  facet_grid(fct_reorder(substr(TITLE_E,10,200),delta,.desc=TRUE)~.,switch = "y", labeller = label_wrap_gen(50)) +
  #scale_alpha_manual(values = c(1,.5)) +
  scale_colour_gradient2(high = "#0571b0", mid = "#f7f7f7", low = "#ca0020") +
  scale_y_continuous(limits = c(0,100), breaks = c(0,25,50,75,100)) +
  deltaTheme

worstData <- sectorDeltas %>%
  inner_join(worst10deltas, by = "QUESTION") %>%
  filter(unitcode != "TBS")

worst <- ggplot(data = worstData, x = abbr_E, group = abbr_E) +
  geom_col(aes(x = abbr_E, y = `2018`), colour = "grey80", fill = "#f7f7f7", width = 0.8) +
  geom_hline(aes(yintercept = `2017`), colour = "grey60") +
  geom_hline(aes(yintercept = `2018`), colour = "grey60") +
  geom_segment(aes(x = abbr_E, xend = abbr_E, y = `2017`, yend = `2018`, colour = delta),
               size = 1, linejoin = "mitre", arrow = arrow(length = unit(0.2, "cm"))) +
  #geom_point(aes(x = abbr_E, y = `2017`, alpha = abbr_E), size = 8, shape = 16, colour = "blue") +
  #geom_point(aes(x = abbr_E, y = `2018`, alpha = abbr_E), size = 8, shape = 16, colour = "red") +
  geom_text(aes(label = `2017`, x = abbr_E, y = `2017`),
            size = 3, colour = "grey30", fontface = "plain", hjust = -0.3, vjust = 0.5) +
  geom_text(aes(label = `2018`, x = abbr_E, y = `2018`),
            size = 3, colour = "grey30", fontface = "bold", hjust = 1.3, vjust = 0.5) +
  geom_text(aes(label = paste0("(",delta,")"), x = abbr_E, y = `2018`, colour = delta),
            size = 3, fontface = "bold", hjust = 2.2, vjust = 0.5) +
  geom_text(aes(label = paste0("ind",INDICATORID), x = abbr_E, y = 0),
            size = 3, colour = "grey50", fontface = "plain", hjust = -0.1, vjust = 0.5) +
  coord_flip() +
  facet_grid(fct_reorder(substr(TITLE_E,10,200),delta)~.,switch = "y", labeller = label_wrap_gen(50)) +
  #scale_alpha_manual(values = c(1,.5)) +
  scale_colour_gradient2(high = "#0571b0", mid = "#f7f7f7", low = "#ca0020") +
  scale_y_continuous(limits = c(0,100), breaks = c(0,25,50,75,100)) +
  deltaTheme

best_ttl <- textGrob("Top Positive Shifts", gp = gpar(fontsize = 10, fontface = "bold", col = "grey30"))
worst_ttl <- textGrob("Top Negative Shifts", gp = gpar(fontsize = 10, fontface = "bold", col = "grey30"))

right.grb <- plot_grid(best_ttl,best,worst_ttl,worst, nrow = 4, rel_heights = c(1,12,1,12))
right.grb 

```

```{r Sector Card - Har & Dis, echo=FALSE, fig.height=8, fig.width=10.5}

sectorHarDis <- question100s %>%
  filter(unitcode %in% c(thisSector, "TBS") & SURVEYR == 2018 & SUBINDICATORID %in% c(12,13)) %>%
  mutate(abbr_E = ifelse(unitcode == thisSector, thisAbbr_E, unitcode)) %>%
  select(QUESTION,TITLE_E,TITLE_F,unitcode,abbr_E,SURVEYR,AGREE,agree_2017) %>%
  mutate(delta = AGREE - agree_2017) %>%
  rename(`2017` = agree_2017, `2018` = AGREE)

har <- ggplot(data = filter(sectorHarDis, QUESTION %in% c("Q48","Q55")), x = abbr_E, group = abbr_E) +
  geom_col(aes(x = abbr_E, y = `2018`), colour = "grey80", fill = "#f7f7f7", width = 0.8) +
  geom_segment(aes(x = abbr_E, xend = abbr_E, y = `2017`, yend = `2018`, colour = delta),
               size = 1, linejoin = "mitre", arrow = arrow(length = unit(0.3, "cm"))) +
  #geom_point(aes(x = abbr_E, y = `2017`, alpha = abbr_E), size = 8, shape = 16, colour = "blue") +
  #geom_point(aes(x = abbr_E, y = `2018`, alpha = abbr_E), size = 8, shape = 16, colour = "red") +
  geom_text(aes(label = paste0(`2017`,"%"), x = abbr_E, y = `2017`),
            size = 3, colour = "grey30", fontface = "plain", vjust = -0.5) +
  geom_text(aes(label = paste0(`2018`,"%"), x = abbr_E, y = `2018`),
            size = 3, colour = "grey30", fontface = "bold", vjust = -0.5) +
  geom_text(aes(label = paste0("(",ifelse(delta>0,paste0("+",delta),delta),"%)"), # Add a "+" to delta if positive
            x = abbr_E, y = (`2017` + delta/2), colour = delta),
            size = 3, fontface = "bold", vjust = 1.5) +
  geom_text(aes(label = abbr_E, x = abbr_E, y = 0),
            size = 3, fontface = "italic", hjust = 1.5, colour = "grey30") +
  coord_flip() +
  facet_grid(.~substr(TITLE_E,10,200),switch = "y", labeller = label_wrap_gen(50)) +
  #scale_alpha_manual(values = c(1,.5)) +
  scale_colour_gradient2(low = "#0571b0", mid = "#f7f7f7", high = "#ca0020") +
  scale_x_discrete(position = "top") +
  deltaTheme +
  theme(
    #axis.text.y = element_text(size = 8),
    strip.text.x = element_text(size = 6))

har_ttl <- textGrob("Victims of Harassment", gp = gpar(fontsize = 10, fontface = "bold", col = "grey30"))
dis_ttl <- textGrob("Victims of Discrimination", gp = gpar(fontsize = 10, fontface = "bold", col = "grey30"))
hd_ttl.grb <- plot_grid(har_ttl,dis_ttl)

hdpc.grb <- ggplot(data = filter(sectorHarDis, QUESTION %in% c("Q48","Q55")), aes(x = abbr_E)) +
  geom_text(aes(label = paste0(abbr_E,": ",`2018`,"%"),y=1, colour = QUESTION), fontface = "bold.italic", size = 4) +
  facet_grid(.~str_wrap(substr(TITLE_E,10,200),45)) +
  scale_x_discrete(position = "bottom") +
  scale_colour_manual(values = c("#7fc97f","#beaed4")) +
  deltaTheme +
  theme(axis.text = element_blank()) +
  theme(strip.text = element_text(size = 8))

#hd.grb <- plot_grid(hd_ttl,hd,nrow=2, rel_heights = c(1,8))

harNatureData <- sectorHarDis %>%
  filter(startsWith(QUESTION,"Q50")) %>%
  mutate(Qshort_E = word(TITLE_E,3, sep = fixed('.'))) %>%
  arrange(desc(unitcode),`2018`) %>%
  mutate(order = row_number())
harNature <- ggplot(harNatureData, aes(x=fct_reorder(str_wrap(substr(Qshort_E,1,50),30), order), y=`2018`)) +
  labs(
    x="Sectors", 
    y="% answering yes in 2018") +
  geom_col(aes(alpha = abbr_E), fill = "#7fc97f") +
  geom_text(hjust=-0.1, vjust=0.5, size=3, colour="grey30", fontface = "bold", 
            aes(label=ifelse(`2018`==0,"-",`2018`), y=0)) +
  coord_flip() +
  facet_grid(.~abbr_E) +
  scale_alpha_manual(values = c(1,.5)) +
  deltaTheme +
  theme(axis.text.y = element_text(size = 6)) +
  theme(axis.title.x = element_text(size = 8)) +
  theme(axis.text.x = element_blank()) +
  theme(strip.text = element_text(colour = "grey30", face = "italic", size = 8))

disTypeData <- sectorHarDis %>%
  filter(startsWith(QUESTION,"Q57")) %>%
  mutate(Qshort_E = word(TITLE_E,3, sep = fixed('.'))) %>%
  arrange(desc(unitcode),`2018`) %>%
  mutate(order = row_number())
disType <- ggplot(disTypeData, aes(x=fct_reorder(str_wrap(substr(Qshort_E,1,50),30), order), y=`2018`)) +
  labs(
    x="Sectors", 
    y="% answering yes in 2018") +
  geom_col(aes(alpha = abbr_E), fill = "#beaed4") +
  geom_text(hjust=-0.1, vjust=0.5, size=3, colour="grey30", fontface = "bold", 
            aes(label=ifelse(`2018`==0,"-",`2018`), y=0)) +
  coord_flip() +
  facet_grid(.~abbr_E) +
  scale_alpha_manual(values = c(1,.5)) +
  deltaTheme +
  theme(axis.text.y = element_text(size = 6)) +
  theme(axis.title.x = element_text(size = 8)) +
  theme(axis.text.x = element_blank()) +
  theme(strip.text = element_text(colour = "grey30", face = "italic", size = 8))

hr_ttl <- textGrob("Nature of Harassment",
                   gp = gpar(fontsize = 10, fontface = "bold", col = "grey30"))
dt_ttl <- textGrob("Type of Discrimination",
                   gp = gpar(fontsize = 10, fontface = "bold", col = "grey30"))

nt_ttl.grb <- plot_grid(hr_ttl,dt_ttl)

nt.grb <- plot_grid(harNature,disType)

hd.grb <- plot_grid(hd_ttl.grb,hdpc.grb,nt_ttl.grb,nt.grb,nrow=4, rel_heights = c(1,5,1,14))  

left.grb <- plot_grid(slp.grb,hd.grb, nrow = 2)

plot_ttl <- paste0("PSES 2018 Report Card - ",sectorName_E) 

plot_ttl.grb <- textGrob(plot_ttl, hjust=0.85,
                     gp = gpar(fontsize = 14, fontface = "bold", col = "grey30"))

plot.grb <- plot_grid(left.grb,right.grb)
plot.grb <- plot_grid(plot_ttl.grb,plot.grb,nrow=2,rel_heights = c(1,20))
plot.grb

ggsave(file.path(mainDir,plotDir,paste0(plot_ttl,".pdf")), plot = plot.grb, height = 8, width = 10.5)
```