---
title: "EE Groups on all Questions"
output: html_notebook
---

```{r setup}
source("pses2018.R")

library(tidyverse)
library(cowplot)

```

```{r Disability Graph, fig.height= 6, fig.width=18}

ee_data <- pses2018 %>% 
  filter(LEVEL1ID == 26, 
         DemoQ %in% c("Q88","dept"),
         SURVEYR == 2018) %>% 
  select(QUESTION,POSITIVE,
         DESCRIP_E,DESCRIP_F,BYCOND,
         DemoQ,DemoQ_E,DemoQ_F,
         INDICATORID,INDICATOR_E,INDICATOR_F) %>%
  arrange(desc(DESCRIP_E),desc(POSITIVE)) %>%
  mutate(QUESTION = str_sub(QUESTION, start = 2)) %>% 
  #mutate(QUESTION = fct_inorder(QUESTION)) %>% 
  filter(DemoQ != "dept") %>% 
  drop_na(POSITIVE) %>% 
  group_by(QUESTION) %>% 
  mutate(delta = diff(POSITIVE)*-1) %>% 
  ungroup() %>% 
  mutate(Difference = fct_rev(ifelse(delta >= 0, "Advantage for persons with a disability", "Disadvantage for persons with a disability"))) %>%
  mutate(DESCRIP_E = fct_rev(DESCRIP_E)) %>%
  mutate(DESCRIP_F = fct_rev(DESCRIP_F)) %>% 
  mutate(INDICATOR_E = fct_reorder(INDICATOR_E, INDICATORID)) %>% 
  mutate(INDICATOR_F = fct_reorder(INDICATOR_F, INDICATORID))
  #mutate(QUESTION = fct_reorder(QUESTION,delta))

line_plot <- ggplot(ee_data, aes(x = QUESTION, y = POSITIVE,
                               group = DESCRIP_E, colour = DESCRIP_E,shape = DESCRIP_E)) +
  scale_shape_manual(values = c(16,21)) +
  scale_colour_manual(values = c("#CD202C","#3095B4")) +
  geom_line() +
  geom_point(fill = "white") +
  labs(colour = NULL, shape = NULL, x = "PSES question number", y = "Positive responses (%)") +
  facet_grid(cols = vars(INDICATOR_E), #rows = vars(DemoQ_E),
            scales = "free", space = "free") +
  theme_classic() +
  theme(legend.position = c(.07,.2),
        axis.text.x = element_text(angle = 90, vjust = 0.5),
        axis.text.y = element_text(angle = 90, hjust = 0.5),
        #panel.background = element_rect(fill = NA, colour = "black"),
        #strip.background = element_rect(colour = NA, fill = "grey90"),
        strip.background = element_blank(),
        strip.text = element_text(size = 8),
        axis.title = element_text(size = 10),
        axis.title.x = element_blank())

diff_plot <- ggplot(ee_data, aes(x = QUESTION, y = delta/2)) +
  geom_col(width = 0.3, fill = "#CD202C") +
  geom_hline(yintercept = 0, colour = "grey30") +
  labs(colour = NULL, fill = NULL, shape = NULL, x = "PSES question number", y = "Delta (disability - no disability)") +
  facet_grid(cols = vars(INDICATOR_E), #rows = vars(DemoQ_E),
            scales = "free", space = "free") +
  scale_y_continuous(expand = expand_scale(add = c(2,6))) +
  theme_classic() +
  theme(legend.position = c(.09,.2),
        axis.text.x = element_text(angle = 90, vjust = 0.5),
        axis.text.y = element_text(angle = 90, hjust = 0.5),
        #panel.background = element_rect(fill = NA, colour = "black"),
        strip.background = element_blank(),
        strip.text = element_blank(),
        axis.title = element_text(size = 10))

descrip_lookup <- distinct(ee_data,BYCOND,DESCRIP_E,DESCRIP_F)

ee_data_wide <- ee_data %>%
  select(-BYCOND,-DESCRIP_F) %>% 
  spread(DESCRIP_E,POSITIVE) %>% 
  rename(disabled = 10, not_disabled = 11) %>% 
  mutate(disabled_delta = ifelse(delta > 0, delta, 0)) %>% 
  mutate(not_disabled_delta = ifelse(delta > 0, 0, delta))

diff_plot2 <- ggplot(ee_data_wide, aes(x = QUESTION)) +
  geom_segment(aes(x = QUESTION, xend = QUESTION, y = not_disabled_delta, yend = disabled_delta)) +
  geom_point(aes(x = QUESTION, y = disabled_delta), colour = "#CD202C", shape = 16) +
  geom_point(aes(x = QUESTION, y = not_disabled_delta), colour = "#3095B4", shape = 21) +
  #scale_shape_manual(values = c(16,21)) +
  #scale_colour_manual(values = c("#CD202C","#3095B4")) +
  #geom_col(width = 0.3, fill = "#CD202C") +
  geom_hline(yintercept = 0, colour = "grey30") +
  labs(colour = NULL, fill = NULL, shape = NULL, x = "PSES question number", y = "Delta (disability - no disability)") +
  facet_grid(cols = vars(INDICATOR_E), #rows = vars(DemoQ_E),
            scales = "free", space = "free") +
  scale_y_continuous(expand = expand_scale(add = c(2,6))) +
  theme_classic() +
  theme(legend.position = c(.09,.2),
        axis.text.x = element_text(angle = 90, vjust = 0.5),
        axis.text.y = element_text(angle = 90, hjust = 0.5),
        #panel.background = element_rect(fill = NA, colour = "black"),
        strip.background = element_blank(),
        strip.text = element_blank(),
        axis.title = element_text(size = 10))

dis_plot <- cowplot::plot_grid(line_plot,diff_plot,ncol = 1)

dis_plot

barb_plot <- ggplot(ee_data, aes(x = QUESTION, y = POSITIVE)) +
  geom_point(aes(fill = DESCRIP_E, colour = DESCRIP_E)) +
  geom_line(aes(x = QUESTION, y = POSITIVE, group = QUESTION,
                colour = Difference))

ggsave(file.path(mainDir,plotDir,"PSES2018@TBS - Persons with a Disability.svg"),
       plot = dis_plot, height = 6, width = 18)
```

```{r Disability Graph - Line Only, fig.height= 3.5, fig.width=16 }

ee_data <- pses2018 %>% 
  filter(LEVEL1ID == 26, 
         DemoQ %in% c("Q88","dept"),
         SURVEYR == 2018) %>% 
  select(QUESTION,POSITIVE,
         DESCRIP_E,DESCRIP_F,BYCOND,
         DemoQ,DemoQ_E,DemoQ_F,
         INDICATORID,INDICATOR_E,INDICATOR_F) %>%
  arrange(desc(DESCRIP_E),desc(POSITIVE)) %>%
  mutate(QUESTION = str_sub(QUESTION, start = 2)) %>% 
  #mutate(QUESTION = fct_inorder(QUESTION)) %>% 
  filter(DemoQ != "dept") %>% 
  drop_na(POSITIVE) %>% 
  group_by(QUESTION) %>% 
  mutate(delta = diff(POSITIVE)*-1) %>% 
  ungroup() %>% 
  mutate(Difference = fct_rev(ifelse(delta >= 0, "Advantage for persons with a disability", "Disadvantage for persons with a disability"))) %>%
  mutate(DESCRIP_E = fct_rev(DESCRIP_E)) %>%
  mutate(DESCRIP_F = fct_rev(DESCRIP_F)) %>% 
  mutate(INDICATOR_E = fct_reorder(INDICATOR_E, INDICATORID)) %>% 
  mutate(INDICATOR_F = fct_reorder(INDICATOR_F, INDICATORID))
  #mutate(QUESTION = fct_reorder(QUESTION,delta))

line_plot_e <- ggplot(ee_data, aes(x = QUESTION, y = POSITIVE,
                               group = DESCRIP_E, colour = DESCRIP_E, shape = DESCRIP_E)) +
  scale_colour_manual(values = c("#CD202C","#3095B4")) +
  scale_shape_manual(values = c(16,21)) +
  geom_line() +
  geom_point(fill = "white") +
  labs(colour = NULL, shape = NULL, x = "Public Service Employee Survey questions", y = "Positive responses (%)") +
  facet_grid(cols = vars(INDICATOR_E), #rows = vars(DemoQ_E),
            scales = "free", space = "free",
            labeller = label_wrap_gen(15)) +
  theme_classic() +
  theme(legend.position = c(.08,.2),
        line = element_line(colour = "grey30"),
        text = element_text(colour = "grey30"),
        axis.text.x = element_text(angle = 90, vjust = 0.5),
        axis.text.y = element_text(angle = 90, hjust = 0.5),
        #panel.background = element_rect(fill = NA, colour = "black"),
        #strip.background = element_rect(colour = NA, fill = "grey90"),
        strip.background = element_blank(),
        strip.text = element_text(size = 8),
        axis.title = element_text(size = 10))
        #axis.title.x = element_blank())

line_plot_f <- ggplot(ee_data, aes(x = QUESTION, y = POSITIVE,
                               group = DESCRIP_F, colour = DESCRIP_F, shape = DESCRIP_F)) +
  scale_colour_manual(values = c("#CD202C","#3095B4")) +
  scale_shape_manual(values = c(16,21)) +
  geom_line() +
  geom_point(fill = "white") +
  labs(colour = NULL, shape = NULL, x = "Questions du Sondage auprès des fonctionnaires fédéraux", y = "Résponses positives (%)") +
  facet_grid(cols = vars(INDICATOR_F), #rows = vars(DemoQ_E),
            scales = "free", space = "free",
            labeller = label_wrap_gen(20)) +
  theme_classic() +
  theme(legend.position = c(.08,.2),
        line = element_line(colour = "grey30"),
        text = element_text(colour = "grey30"),
        axis.text.x = element_text(angle = 90, vjust = 0.5),
        axis.text.y = element_text(angle = 90, hjust = 0.5),
        #panel.background = element_rect(fill = NA, colour = "black"),
        #strip.background = element_rect(colour = NA, fill = "grey90"),
        strip.background = element_blank(),
        strip.text = element_text(size = 8),
        axis.title = element_text(size = 10))

line_plot_e
line_plot_f

ggsave(file.path(mainDir,plotDir,"PSES2018@TBS - Persons with a Disability (line).svg"),
       plot = line_plot_e, height = 3.5, width = 16)

ggsave(file.path(mainDir,plotDir,"SAFF2018@TBS - Personnes handicapées (ligne).svg"),
       plot = line_plot_f, height = 3.5, width = 16)

```